services:
  maps-proxy-api:
    container_name: maps-proxy-api
    image: ${DOCKER_REGISTRY-}maps-proxy-api
    build:
      context: .
      dockerfile: src/MapsProxyApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:443"
    env_file:
      - path: ./default.env
        required: true

  maps-stats-ui:
    container_name: maps-stats-ui
    image: ${DOCKER_REGISTRY-}maps-stats-ui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    ports:
      - "5010:8080"
      - "5011:8081"
    env_file:
      - path: ./default.env
        required: true

  maps-stats-api:
    container_name: maps-stats-api
    image: ${DOCKER_REGISTRY-}maps-stats-api
    build:
      context: .
      dockerfile: src/StatsApi/Dockerfile
    ports:
      - "5002:8080"
      - "5003:8081"
    env_file:
      - path: ./default.env
        required: true

  postgres-server:
    container_name: postgres-server
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - maps_postgres_data:/var/lib/postgresql/data
      - ./init_pg.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - path: ./default.env
        required: true 

  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - postgres-server
    volumes:
      - maps_pgadmin:/home/shared  
    env_file:
      - path: ./default.env
        required: true
   
volumes:
  maps_postgres_data:
  maps_pgadmin:
