CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "UsageLimits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "UsedTimes" integer NOT NULL,
    "MaxUses" integer NOT NULL,
    CONSTRAINT "PK_UsageLimits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UsageLimits_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UsageLimits_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UsageLimits_ServiceId" ON "UsageLimits" ("ServiceId");

CREATE INDEX "IX_UsageLimits_UserId" ON "UsageLimits" ("UserId");

CREATE INDEX "IX_Users_Token" ON "Users" ("Token");

INSERT INTO public."Users"("Id","Token") VALUES ('1','8c039db1-39e5-45ec-a2a7-c6ded5d61487');

INSERT INTO public."Services"("Id","Name") VALUES ('1', 'A06_ATE_TE_WGS84');
INSERT INTO public."Services"("Id","Name") VALUES ('2', 'A05_EGRNI_WGS84');
INSERT INTO public."Services"("Id","Name") VALUES ('3', 'A01_ZIS_WGS84');

INSERT INTO public."UsageLimits"("Id", "UserId", "ServiceId", "UsedTimes", "MaxUses") VALUES ('1', '1', '1', '0', '200');
INSERT INTO public."UsageLimits"("Id", "UserId", "ServiceId", "UsedTimes", "MaxUses") VALUES ('2', '1', '2', '0', '200');
INSERT INTO public."UsageLimits"("Id", "UserId", "ServiceId", "UsedTimes", "MaxUses") VALUES ('3', '1', '3', '0', '200');

