CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "UsedTimes" integer NOT NULL,
    "MaxUses" integer NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);

INSERT INTO public."Services"("Id","Name", "UsedTimes", "MaxUses") VALUES ('1', 'A06_ATE_TE_WGS84', '0', '200');
INSERT INTO public."Services"("Id","Name", "UsedTimes", "MaxUses") VALUES ('2', 'A05_EGRNI_WGS84', '0', '200');
INSERT INTO public."Services"("Id","Name", "UsedTimes", "MaxUses") VALUES ('3', 'A01_ZIS_WGS84', '0', '200');
